### ISSUE TITLE
Tks are not being recorded

### ISSUE THREAD

**Issue by 710Gaming** [kyleshepherd/discord-tk-bot#6]
The bot was working fine until yesterday 5/3/21. The app would not record any TKs or respond to any commands.

**Comment by kyleshepherd** [comment]
I sent this message out via the bot to all the servers, although some weren't able to receive it so I'll leave this issue open with context:

Hey everyone, Kyle here. Sorry to say but Tarkov TK has shut down. The cost of hosting the bot has risen to over $30 a month, and as it doesn't generate income I can't justify keeping it running.

The code for the bot is available here on Github https://github.com/kyleshepherd/discord-tk-bot so if anyone would like to run their own then feel free (worth noting the code could do with a fair bit of refactoring).

I'm available to contact via my Twitter if anyone has any questions about running their own version, or receiving their server data https://twitter.com/kyleshepherddev?lang=en

**Comment by 710Gaming** [comment]
Okay sorry to hear that I would love to be able to have this run again. Thank you so much for your help.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
